# Generated by Django 2.2.1 on 2023-01-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('1', 'LOVE'), ('2', 'LIT'), ('3', 'LIKE'), ('4', 'WOW'), ('5', 'HAHA'), ('6', 'THUMBS-UP'), ('7', 'THUMBS-DOWN'), ('8', 'SAD'), ('9', 'ANGRY')], max_length=20),
        ),
    ]
