# Generated by Django 2.2.1 on 2023-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0002_auto_20230131_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('LOVE', 'LOVE'), ('LIT', 'LIT'), ('LIKE', 'LIKE'), ('WOW', 'WOW'), ('HAHA', 'HAHA'), ('THUMBS-UP', 'THUMBS-UP'), ('THUMBS-DOWN', 'THUMBS-DOWN'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], max_length=20),
        ),
    ]
